name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby-version: ['3.2', '3.3', '3.4']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems
      
      - name: Run tests
        run: bundle exec rspec
        env:
          ZEPLIN_API_TOKEN: ${{ secrets.ZEPLIN_API_TOKEN || 'test_token' }}
      
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report-${{ matrix.ruby-version }}
          path: coverage/
          if-no-files-found: ignore

  bearer:
    name: Bearer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Bearer
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc  # v2
        with:
          scanner: 'sast,secrets'
          severity: 'critical,high,medium,low'

  actions_security:
    name: GitHub Actions Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Run GitHub Actions security audit
        id: audit
        uses: twinsunllc/github-actions-security-checker@965263a11209927fe078a206aee0aba3acc1ae58  # v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allowlist: |
            twinsunllc

      - name: Upload audit report
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        if: always()
        with:
          name: action-security-report
          path: action-security-report.md
          retention-days: 30